In [2]:
!pip install faker

Collecting faker
  Downloading faker-40.23.0-py3-none-any.whl.metadata (16 kB)
Downloading faker-40.23.0-py3-none-any.whl (2.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 78.0 MB/s eta 0:00:00
Installing collected packages: faker
Successfully installed faker-40.23.0

In [3]:
import pandas as pd
import numpy as np
from faker import Faker
import random
from datetime import datetime, timedelta

In [4]:
fake = Faker("en_IN")

random.seed(42)
np.random.seed(42)
Faker.seed(42)

In [5]:
sales_reps = pd.DataFrame({
    "sales_rep_id": range(1, 11),
    "sales_rep_name": [
        "Aarav Sharma",
        "Priya Nair",
        "Rahul Verma",
        "Sneha Gupta",
        "Karan Mehta",
        "Neha Kapoor",
        "Rohan Das",
        "Ananya Roy",
        "Vivek Singh",
        "Meera Joshi"
    ],
    "experience_years": [2,4,1,5,3,2,6,4,7,3],
    "region": [
        "North",
        "South",
        "East",
        "West",
        "North",
        "South",
        "East",
        "West",
        "North",
        "South"
    ]
})

sales_reps

   sales_rep_id sales_rep_name  experience_years region
0             1   Aarav Sharma                 2  North
1             2     Priya Nair                 4  South
2             3    Rahul Verma                 1   East
3             4    Sneha Gupta                 5   West
4             5    Karan Mehta                 3  North
5             6    Neha Kapoor                 2  South
6             7      Rohan Das                 6   East
7             8     Ananya Roy                 4   West
8             9    Vivek Singh                 7  North
9            10    Meera Joshi                 3  South

In [6]:
sales_reps.to_csv("sales_representatives.csv", index=False)

In [7]:
from google.colab import files
files.download("sales_representatives.csv")

In [8]:
products = pd.DataFrame({
    "product_id": [1,2,3],
    "product_name": [
        "Starter",
        "Growth",
        "Enterprise"
    ],
    "monthly_price": [
        999,
        2999,
        9999
    ],
    "category": [
        "SMB",
        "SMB",
        "Enterprise"
    ]
})

products

   product_id product_name  monthly_price    category
0           1      Starter            999         SMB
1           2       Growth           2999         SMB
2           3   Enterprise           9999  Enterprise

In [9]:
products.to_csv("products.csv", index=False)

In [10]:
campaigns = pd.DataFrame({
    "campaign_id":[1,2,3,4,5],
    "campaign_name":[
        "LinkedIn Ads",
        "Google Ads",
        "Referral Program",
        "Cold Email",
        "Organic Website"
    ],
    "channel":[
        "LinkedIn",
        "Google",
        "Referral",
        "Email",
        "Website"
    ],
    "budget":[
        500000,
        400000,
        150000,
        100000,
        200000
    ]
})

campaigns

   campaign_id     campaign_name   channel  budget
0            1      LinkedIn Ads  LinkedIn  500000
1            2        Google Ads    Google  400000
2            3  Referral Program  Referral  150000
3            4        Cold Email     Email  100000
4            5   Organic Website   Website  200000

In [11]:
campaigns.to_csv("marketing_campaigns.csv", index=False)

In [12]:
industries = [
    "SaaS",
    "FinTech",
    "Healthcare",
    "EdTech",
    "E-commerce",
    "Manufacturing",
    "Real Estate",
    "Marketing",
    "Logistics",
    "HR Tech"
]

company_sizes = [
    "Small",
    "Medium",
    "Enterprise"
]

countries = [
    "India",
    "USA",
    "UK",
    "Singapore",
    "Australia"
]

In [13]:
lead_data = []

for lead_id in range(1, 10001):

    campaign_id = random.choices(
        population=[1,2,3,4,5],
        weights=[30,25,15,20,10],
        k=1
    )[0]

    lead_source = {
        1:"LinkedIn",
        2:"Google Ads",
        3:"Referral",
        4:"Cold Email",
        5:"Organic Website"
    }[campaign_id]

    company_size = random.choices(
        ["Small","Medium","Enterprise"],
        weights=[55,30,15],
        k=1
    )[0]

    lead_data.append({
        "lead_id": lead_id,
        "company_name": fake.company(),
        "industry": random.choice(industries),
        "company_size": company_size,
        "country": random.choice(countries),
        "lead_source": lead_source,
        "campaign_id": campaign_id,
        "assigned_sales_rep_id": random.randint(1,10),
        "created_date": fake.date_between(
            start_date="-2y",
            end_date="today"
        )
    })

In [14]:
leads = pd.DataFrame(lead_data)

leads.head()

,lead_id,company_name,industry,company_size,country,lead_source,campaign_id,assigned_sales_rep_id,created_date
0,1,"Choudhury, Bakshi and Maharaj",E-commerce,Small,USA,Referral,3,4,2024-12-24
1,2,Chaudry Ltd,Logistics,Small,India,LinkedIn,1,10,2025-12-21
2,3,"Chahal, Sami and Balay",EdTech,Small,USA,Google Ads,2,9,2024-07-19
3,4,Kaul PLC,Logistics,Medium,Singapore,Referral,3,4,2025-09-11
4,5,"Issac, Saini and Kannan",SaaS,Small,USA,Google Ads,2,7,2025-05-22

In [15]:
leads.to_csv("leads.csv", index=False)

In [17]:
activity_types = [
    "Call",
    "Email",
    "LinkedIn Message",
    "WhatsApp",
    "Demo Meeting"
]

activity_outcomes = [
    "Interested",
    "Follow-up Needed",
    "No Response",
    "Demo Scheduled",
    "Rejected"
]

In [18]:
activities = []

activity_id = 1

for _, lead in leads.iterrows():

    num_activities = random.randint(1,6)

    last_date = lead["created_date"]

    for i in range(num_activities):

        activity_date = last_date + timedelta(
            days=random.randint(1,10)
        )

        last_date = activity_date

        activities.append({
            "activity_id": activity_id,
            "lead_id": lead["lead_id"],
            "sales_rep_id": lead["assigned_sales_rep_id"],
            "activity_date": activity_date,
            "activity_type": random.choice(activity_types),
            "response_time_hours": random.randint(1,72),
            "outcome": random.choice(activity_outcomes)
        })

        activity_id += 1

In [19]:
activities = pd.DataFrame(activities)

activities.head()

,activity_id,lead_id,sales_rep_id,activity_date,activity_type,response_time_hours,outcome
0,1,1,4,2024-12-25,Call,64,No Response
1,2,1,4,2024-12-27,Demo Meeting,49,No Response
2,3,1,4,2024-12-28,Call,8,Rejected
3,4,1,4,2024-12-31,LinkedIn Message,53,Rejected
4,5,2,10,2025-12-27,Demo Meeting,55,Follow-up Needed

In [20]:
activities = pd.DataFrame(activities)

activities.head()

,activity_id,lead_id,sales_rep_id,activity_date,activity_type,response_time_hours,outcome
0,1,1,4,2024-12-25,Call,64,No Response
1,2,1,4,2024-12-27,Demo Meeting,49,No Response
2,3,1,4,2024-12-28,Call,8,Rejected
3,4,1,4,2024-12-31,LinkedIn Message,53,Rejected
4,5,2,10,2025-12-27,Demo Meeting,55,Follow-up Needed

In [21]:
activities.shape

(34852, 7)

In [22]:
activities.to_csv("activities.csv", index=False)

In [27]:
conversion_rates = {
    "Referral": 0.40,
    "LinkedIn": 0.30,
    "Organic Website": 0.22,
    "Google Ads": 0.18,
    "Cold Email": 0.10
}

deals = []

deal_id = 1

for _, lead in leads.iterrows():

    probability = conversion_rates[lead["lead_source"]]
    random_number = random.random()

    # Decide current stage
    if random_number < probability:
        stage = "Won"
        status = "Closed Won"

    elif random_number < probability + 0.10:
        stage = "Negotiation"
        status = "Open"

    elif random_number < probability + 0.20:
        stage = "Proposal Sent"
        status = "Open"

    elif random_number < probability + 0.35:
        stage = "Demo Scheduled"
        status = "Open"

    elif random_number < probability + 0.55:
        stage = "Qualified"
        status = "Open"

    elif random_number < probability + 0.80:
        stage = "Contacted"
        status = "Open"

    else:
        stage = "Lost"
        status = "Closed Lost"

    # Product assignment
    if lead["company_size"] == "Enterprise":
        product_id = 3
        deal_value = random.randint(15000, 50000)

    elif lead["company_size"] == "Medium":
        product_id = random.choice([2, 3])
        deal_value = random.randint(5000, 18000)

    else:
        product_id = random.choice([1, 2])
        deal_value = random.randint(1000, 7000)

    deals.append({
        "deal_id": deal_id,
        "lead_id": lead["lead_id"],
        "sales_rep_id": lead["assigned_sales_rep_id"],
        "product_id": product_id,
        "stage": stage,
        "status": status,
        "deal_value": deal_value if stage == "Won" else 0,
        "close_date": lead["created_date"] + timedelta(days=random.randint(7,60))
    })

    deal_id += 1

In [28]:
deals = pd.DataFrame(deals)

deals.head()

,deal_id,lead_id,sales_rep_id,product_id,stage,status,deal_value,close_date
0,1,1,4,1,Negotiation,Open,0,2025-01-21
1,2,2,10,2,Won,Closed Won,5063,2026-02-18
2,3,3,9,2,Negotiation,Open,0,2024-08-26
3,4,4,4,3,Won,Closed Won,5540,2025-10-06
4,5,5,7,1,Contacted,Open,0,2025-07-12

In [29]:
deals["stage"].value_counts()

stage
Won               2339
Qualified         2011
Contacted         1908
Demo Scheduled    1501
Proposal Sent     1049
Negotiation        949
Lost               243
Name: count, dtype: int64

In [30]:
deals.to_csv("deals.csv", index=False)

In [31]:
print(sales_reps.shape)
print(products.shape)
print(campaigns.shape)
print(leads.shape)
print(activities.shape)
print(deals.shape)

(10, 4)
(3, 4)
(5, 4)
(10000, 9)
(34852, 7)
(10000, 8)